version: '3'
services:
  app:
    image: sightseeker/keycloak-demo
    build: .
    ports:
      - 8888:8080
    depends_on:
      - keycloak
    tty: true
    volumes:
      - ./target:/opt/wildfly-swarm
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
  keycloak:
    image: jboss/keycloak
    environment: 
      MYSQL_ADDR: mysql
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8081:8080
    depends_on:
      - mysql
volumes:
  mysql_data:
      driver: local
